version: '3.3'

services:
  frontend:
    container_name: my-blog-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - /frontend/node_modules
      - ./:/frontend