version: '3.3'

services:
  frontend:
    container_name: my-blog-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /node_modules
      - ./:/frontend