version: '3.3'

services:
  frontend:
    container_name: my-blog-frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - /frontend/node_modules
      - ./src/frontend:/frontend